# Generated by Django 5.0.2 on 2024-02-07 04:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('body', models.TextField(verbose_name='Text')),
                ('image', models.ImageField(upload_to='news/images/', verbose_name='Image')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('status', models.CharField(choices=[('PU', 'Published'), ('DR', 'Draft')], default='DR', max_length=2, verbose_name='Status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.category', verbose_name='Category')),
            ],
            options={
                'ordering': ['-published_time'],
            },
        ),
    ]
