# Generated by Django 5.0.2 on 2024-02-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='Image'),
        ),
    ]
