# Generated by Django 5.0.2 on 2024-02-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='Image'),
        ),
    ]
